name: CD - Azure Bicep

on:
  repository_dispatch:
    branches:
      - main
    paths:
      - "infrastructure/**"

permissions:
  id-token: write
  contents: read

env:
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  LOCATION: ${{ github.event.client_payload.r16c6e272ee4e470ca7ad9a648001b4a3 }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}"
      - name: Testing output
        run: echo "${{ env.LOCATION }}"
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      - uses: azure/arm-deploy@v1
        id: deploy
        name: Deploy infrastructure
        with:
          failOnStdErr: false
          deploymentName: ${{ github.run_number }}
          scope: subscription
          region: ${{ env.LOCATION }}
          subscriptionId: ${{ env.ARM_SUBSCRIPTION_ID }}
          template: ./infrastructure/main.bicep
          parameters: ./infrastructure/parameters.bicepparam
